### ISSUE TITLE
Traingle Example throws error.

### ISSUE THREAD

**Issue by SuryaprakashBS** [rajveermalviya/go-webgpu-examples#1]
I tried to run triangle example in my machine. But, it throws error like,

`# to_do/triangle-webview
./webview_t1.go:52:19: undefined: wgpu.CreateSurface
./webview_t1.go:54:23: undefined: wgpu.RequestAdapter
./webview_t1.go:226:19: undefined: wgpu.GenerateReport`

So I added following code in surface_darwin.go

`func getInstanceDescriptor() *wgpu.InstanceDescriptor {
	return &wgpu.InstanceDescriptor{}
}`

then I created Instance using Instance Descriptor and replaced instance instead of wgpu.

But now it throws panic

**Comment by rajveermalviya** [comment]
seems like you are trying to re-implement the example (seeing `webview.go`), so can't tell if the problem is in your code or not.

can you try running the example from this repo directly?
`go run github.com/rajveermalviya/go-webgpu-examples/triangle@latest`

**Comment by SuryaprakashBS** [comment]
Now it works fine. How can I see the code?

**Comment by SuryaprakashBS** [comment]
It's woking fine bro. Which version of wgpu it using? Could you tell? 

I think version of the wgpu package is the root cause of the error in my side.

**Comment by rajveermalviya** [comment]
I have just updated the go-webgpu version in this repo to v0.15.1.
so [go-webgpu v0.15.1](https://github.com/rajveermalviya/go-webgpu-examples/blob/4856f5e8c05091b18114f3c100084c21fb4fd08a/go.mod#L8) -> [wgpu-native v0.15.1.2](https://github.com/rajveermalviya/go-webgpu/blob/2b956bb49f54eec60ce9ab611d92badfaeb04b5f/.github/workflows/build-wgpu.yml#L7) -> [wgpu v0.15.1](https://github.com/gfx-rs/wgpu-native/blob/1adb5576cb566432f38b8d8d9891630b94820133/Cargo.toml#L34)

which is latest version currently

**Comment by SuryaprakashBS** [comment]
Thanks bro.
